import type { NextPage } from 'next'
import Head from 'next/head'


const About: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Marko Pavic | About me</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <h1>About page</h1>
            </main>
        </div>
    )
}

export default About
