import Head from "next/head";

interface IBlogProps {}

const Blog = ({}: IBlogProps) => {
	return (
		<>
			<Head>
				<title>Marko Pavic | Blog</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div>
				<h1>Blog page</h1>
			</div>
		</>
	);
};

export default Blog;
