import type { NextPage } from 'next'
import Head from 'next/head'


const Components: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Marko Pavic | Components</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <h1>Components page</h1>
            </main>
        </div>
    )
}

export default Components
