import type { NextPage } from "next";
import Head from "next/head";
import { Section } from "src/components/section/section";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Marko Pavic | Javascript Developer</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-center">Home page</h1>
        <Section>
          <h1>HERO</h1>
        </Section>
      </main>
    </div>
  );
};

export default Home;
