import type { NextPage } from "next";
import Head from "next/head";

// components
import { HeroSection } from "src/sections/home/heroSection";
import { PresentationSection } from "src/sections/home/presentationSection";

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Marko Pavic | Javascript Developer</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div></div>
		</>
	);
};

export default Home;
