import type { NextPage } from "next";
import Head from "next/head";

const Projects: NextPage = () => {
	return (
		<>
			<Head>
				<title>Marko Pavic | Projects</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div>
				<h1>Projects page</h1>
			</div>
		</>
	);
};

export default Projects;
